version: '3'
services:  
  arangodb:
    image: arangodb/arangodb:latest
    environment:
      ARANGO_ROOT_PASSWORD: defaults
    ports:
      - "8529:8529"
    volumes:
      - ./datas:/var/lib/arangodb3

  backend:
    build: ./
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: http://arangodb:8529
      DATABASE_USER: root
      DATABASE_PASS: rootpassword
    depends_on:
      - arangodb