version: '3'
services:
  arangodb:
    image: arangodb/arangodb:latest
    environment:
      ARANGO_ROOT_PASSWORD: defaults
    ports:
      - "8529:8529"
    volumes:
      - ./datas:/var/lib/arangodb3
